# For more information: https://laravel.com/docs/sail
version: '3'
services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        build:
            context: ./docker/nginx
        restart: unless-stopped
        # depends_on:
        #    - app
        ports:
            - "80:80"
            - "443:443"
        volumes:        
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
            - ./docker/certbot/conf:/etc/letsencrypt
            - ./docker/certbot/www:/var/www/certbot
        depends_on:
            - app
            - certbot
        networks:
            - apiEstetify
    certbot:
        image: certbot/certbot
        restart: unless-stopped
        volumes:
            - ./docker/certbot/conf:/etc/letsencrypt
            - ./docker/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
        networks:
            - apiEstetify
    app:
        build:
            context: ./docker/8.0
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        container_name: app
        environment:
            WWWUSER: '${WWWUSER}'
        working_dir: /var/www
        volumes:
            - ./:/var/www
            # - ./docker/8.0/php.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - apiEstetify
        depends_on:
            - mysql
            - redis
            # - meilisearch
            # - selenium
    mysql:
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'estetifymysql:/var/lib/mysql'
        networks:
            - apiEstetify
        healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
          retries: 3
          timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'estetifyredis:/data'
        networks:
            - apiEstetify
        healthcheck:
          test: ["CMD", "redis-cli", "ping"]
          retries: 3
          timeout: 5s
    
networks:
    apiEstetify:
        driver: bridge
volumes:
    estetifymysql:
        driver: local
    estetifyredis:
        driver: local
    # sailmeilisearch:
    #     driver: local
