# This is a basic workflow to help you get started with Actions

name: CI main

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: warsaw

    steps:      
    - name: Touch repo
      run: echo "hi"
      
    #- name: Updating Code
    #  run: git pull origin main

    #- name: Starting Application
    #  run: docker-compose up -d

    #- name: Copy .env if it doesn't exist
    #  run: docker-compose exec -T app php -r "file_exists('.env') || copy('.env.example', '.env');"

    #- name: Install composer dependences
    #  run: docker-compose exec -T app composer install

    - name: Running Migrations
      run: docker-compose exec -T app php artisan migrate --force
